program_set:
  sys_name: system
  calc_mm: true
  calc_pbsa: true
  trj: md.xtc
  tpr: md.tpr
  ndx: index.ndx
  rec_grp: Protein
  lig_grp: ''
  start_time: 0.0
  end_time: .inf
  dt: 1000.0
  ie_multiple: 10
  fix_pbc: true
  cfac: 3
  fadd: 10.0
  df: 0.5
  radius_type: mBondi
  ala_scan_range: ''
mm_set:
  cutoff: .inf
  electric_screening: 1
pbe_set:
  temp: 298.15
  pdie: 2.0
  sdie: 78.4
  pb_solver: npbe
  bcfl: mdh
  srfm: smol
  chgm: spl4
  swin: 0.3
  srad: 1.4
  sdens: 10
  ions:
  - charge: 1.0
    conc: 0.15
    radius: 0.95
  - charge: -1.0
    conc: 0.15
    radius: 1.81
  calc_force: false
  calc_energy: comps
pba_set:
  temp: 298.15
  srfm: sacc
  swin: 0.3
  srad: 1.4
  gamma: 1.0
  press: 0.0
  bconc: 0.0
  sdens: 10.0
  dpos: 0.2
  grid:
  - 0.1
  - 0.1
  - 0.1
  calc_force: false
  calc_energy: total
